### ISSUE TITLE
[FEATURE] My Page - Prefer Data

### ISSUE THREAD

**Issue by Mnseo** [27-kusitms-6/Frontend#16]
`[FEATURE]` Prefer Data

## ToDo

- [ ] Setting Prefer Data
- [ ] Personal Route Input UI
- [ ] Personal Route Input Kotlin

## Comment
