### ISSUE TITLE
[FEATURE] 기본 회원가입, 로그인 

### ISSUE THREAD

**Issue by Mnseo** [27-kusitms-6/Frontend#4]
## 내용
- 서버 연결 전 기본 로그인/회원 가입 프로세스

## ToDo
- [ ] 회원 가입: 이메일(또는 아이디), 비밀번호, 전화번호, 이름 받기 
- [ ] 회원 가입 확인
  - [ ] 특수 문자 x , Input 1줄
  - [ ] 아이디 중복 확인 
-  [ ] 로그인
