### ISSUE TITLE
[FEATURE] Firebase 세팅 

### ISSUE THREAD

**Issue by Mnseo** [27-kusitms-6/Frontend#5]
## 내용
- fcm 을 위한 firebase 세팅

## ToDo
- [ ] Firebase 구성 파일 추가 (로컬)
- [ ] Firebase SDK 추가 
- [ ] Firebase SDK 적용시점에서 token 값 확인 가능 검토
